# Generated by Django 4.2.5 on 2023-09-16 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço total')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
